# Default values
resources:
  maxCPU: 250m
  maxMemory: 0.25Gi

  cpu: 200m
  memory: 0.2Gi

utilization:
  cpu: 40
  memory: 35

container:
  image: dgansky/k8s-test:latest

autoscaling:
  min: 3
  max: 6

configMap:
  username: PRODUCTION